@Restaurants.API_HostAddress = https://localhost:7186
@token = CfDJ8JkfaPYyrzRPuEHO__lupswOYnBzNosCiLwCDRlqK7fraHHa6lcA9iCtpfLb-uKlOya8ioKDaAwTMuIHf1JkgFPCKMMyS4PgQrEYANERGZDF0fRW80b-9zjqMg1-V-riiKF7kwRrGCbnTk2RfMAQ6N38SVq7yQPGPSL7tsDGMG74i4O_5c7amj_MRq3hNt99Uv3bSh6jx3Q5VeCyZvORU5js20YsnRsZfwFEaq05U55mcq9_nHnYZQn137ON7h3FCqR5sg5hUzX17RnlR3vIIz3bog5zpY9DV6aOO4O5hCDpxOwFFuSMy04DNKRGvJGCDtuY1O91-CWd2SZN_l_ZN_O6215jfORiJdTseiRV_jgkX3uWcUkwgAQT3e3YLTzpZx860CWGYBq7KQBnQzUIfbdywxImoGNPzV3ZheXpHCEaZGF2LsMospm9UwaPqappfT8Rout5iuPb1nAe0o5A4qGVKn0jxNonfJbxH1SBMoRg5tYBEesUTtyyjIlRtNFcuWvz-B4F8V4YoZIZUdrPz6cYgkFRcBob4EUTe7wZfNCmUntheRNz5iKlYHQcKQmvC6yeEgRvwaUEqldQl-n4x3Uz9NzWNAenf47I_HEheQDt4cGELDg8W7czQt75snhGUGlo-8gUuRPDDeF8sYUgy3ZNrd95AX-76DmvFdG88WOHfjxiaUOZzd0zgiSC6HQ2FZphpEIerXROqbQNpChpaIp293-YpwHy6lfhsXii-XriG6RUju6fqmMizC6Zd2Ls623ujtcAGOUZ2XZ7rPu4WkOD5qxipyaQ04YoB9bW24lz

### register new identity user
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password1!"
}

### login with user
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

### set role for user
POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userEmail": "owner2@test.com",
  "roleName": "Owner"
}


### Get all restaurants (with search phrase)
GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=hot&pageSize=11113&pageNumber=2
Authorization: Bearer {{token}}

### Get all restaurants (without search phrase)

GET {{Restaurants.API_HostAddress}}/api/restaurants?pageSize=30&pageNumber=1&sortBy=Description&sortDirection=Ascending
Authorization: Bearer {{token}}

### Get a restaurant by id
GET {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}

###
// add new restaurant (not valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "New Restaurant",
    "Description": "",
    "Category": "Missing Category",
    "HasDelivery": true,
    "ContactEmail": "dummy@@email.com",
    "ContactNumber": "a1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123456"
}

###
// add new restaurant (valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Owner 2 Restaurant 2",
    "Description": "Scorching Hot",
    "Category": "Japanese",
    "HasDelivery": true,
    "ContactEmail": "dummy@email.com",
    "ContactNumber": "1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123-4567"
}

###
// update restaurant (not valid)
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "I was renamed",
    "Description": "yoyoyo",
    "HasDelivery": true
}

###
// update restaurant (valid)
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
    "Name": "New Restaurant (edit 1)",
    "Description": "New Restaurant Description (edit 1)",
    "HasDelivery": false
}

###
// delete restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}

###
// add a new dish to a restaurant (invalid)
POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Godzila Cheeese Burger",
    "Description": "Super Cheezy, Super Calorie",
    "Price": -1,
    "KiloCalories": -1
}

###
// add a new dish to a restaurant (valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Godzila Cheeese Burger 2",
    "Description": "Super Cheezy, Super Calorie 2",
    "Price": 12.99,
    "KiloCalories": 1200
}

###
// get all dishes for a specific restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/
Authorization: Bearer {{token}}

###
// get dish for a specific restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/5
Authorization: Bearer {{token}}

###
// remove dishes from a restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

