@Restaurants.API_HostAddress = https://localhost:7186

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5

###

// add new restaurant (not valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Ne",
    "Description": "",
    "Category": "Missing Category",
    "HasDelivery": true,
    "ContactEmail": "dummy@@email.com",
    "ContactNumber": "a1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123456"
}

###

// add new restaurant (valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Godzila Burger",
    "Description": "Scorching Hot",
    "Category": "Japanese",
    "HasDelivery": true,
    "ContactEmail": "dummy@email.com",
    "ContactNumber": "1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123-4567"
}

###

// delete restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/88

