@Restaurants.API_HostAddress = https://localhost:7186
@token = CfDJ8JkfaPYyrzRPuEHO__lupsxYbRSlSONXpqy6uGVqkPYqFMDBP1vnMUNnGNsBn3TK8ET-Z-p9dlm7rSC9U7Yz5JwfxQ4duoq2ue_OKRB-x0zoIpiD6JgHS72xOExVR7p1I4mhPL6IMY3MHda6CMisq3bejUwm2JB7KBdv5GOzT_XZIU9P-BEsxKO4W86hFwqXF23GW2VJq41q8FEu3uTB6TEm0vZ8U4l313s-ESRa_8ugf5dY2XOoHKxI40UPlSqtvtvlI6qit8wCUS52MJ_7zJQEuooqjSkFJ-ik1Rxu04b2H056k2ORWBU7aWvd-ShNDjuNOxaLzj1VMR_QnHXXfZOoxK0vVuGnkp7Arolq9TImDj7EBumqd9IY_UbGZmbFAOR7ZnlYymdNqroWv1c4yKZpGX94DpWkNrYOx83kbYJ2zrNr-8uU3kqDi75BxipiP6Sivvrde89_-U0NzQZyofQ8MqnBLLRxOVn4uGLJYbBEdnYUk2mD7gDzjbgMucJFCv4npJZU8JkgYer9ejDrZSmR1Pbqm6GieKBEIyydYOzOgg089JfY3pYhHXPRMCfzr20vdxsUVyXY06gh2RlYbWoBU7aJiitU5ldZAgucoAyIW4AKmNjTLdgEbEYO17GmIEIa-mfTPMW2_y3t20i6re_7I-aXFH0_VIqaIyg3sXw71v775o-MOUa-fHyjc5KRnw_Ke6jnHM6s3qyRRdg0EWC0GVuB_Kdz0NVuJcckf-aeAgTJM5fwWkf_m13lxFTJo2RajbE3iTyef1fYY4qprb_MU7QHTuF1FsqsvqTovOiDPuYofKk3yDnKPHsn7uYcFcXl0VezF1KeXWLlCNWgqbsRsvRJtIhFr42D6_Cc-jEwEOfxFpZv16YIlCZaoeykWVtqHAwyoUL4aQQ27m7O6yw

### register new identity user
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

### login with user
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

### set role for user
POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userEmail": "admin@test.com",
  "roleName": "Admin"
}


### Get all restaurants
GET {{Restaurants.API_HostAddress}}/api/restaurants

### Get a restaurant by id
GET {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}

###
// add new restaurant (not valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Ne",
    "Description": "",
    "Category": "Missing Category",
    "HasDelivery": true,
    "ContactEmail": "dummy@@email.com",
    "ContactNumber": "a1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123456"
}

###
// add new restaurant (valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Godzila Burger Max Again by Owner",
    "Description": "Scorching Hot",
    "Category": "Japanese",
    "HasDelivery": true,
    "ContactEmail": "dummy@email.com",
    "ContactNumber": "1234567890",
    "City": "New City",
    "Street": "New Street",
    "PostalCode": "123-4567"
}

###
// update restaurant (not valid)
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "I was renamed",
    "Description": "yoyoyo",
    "HasDelivery": true
}

###
// update restaurant (valid)
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
    "Name": "New Restaurant (edit 1)",
    "Description": "New Restaurant Description (edit 1)",
    "HasDelivery": false
}

###
// delete restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}

###
// add a new dish to a restaurant (invalid)
POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Godzila Cheeese Burger",
    "Description": "Super Cheezy, Super Calorie",
    "Price": -1,
    "KiloCalories": -1
}

###
// add a new dish to a restaurant (valid)
POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "Name": "Godzila Cheeese Burger 2",
    "Description": "Super Cheezy, Super Calorie 2",
    "Price": 12.99,
    "KiloCalories": 1200
}

###
// get all dishes for a specific restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/
Authorization: Bearer {{token}}

###
// get dish for a specific restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/5
Authorization: Bearer {{token}}

###
// remove dishes from a restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

